/*
 * File Name : crc8.c
 * Author    : Alexey Yu. Illarionov, INI UZH Zurich
 *             <ayuillarionov@ini.uzh.ch>
 *
 * Created   : Mon 19 Nov 2018 05:10:45 PM CET
 * Modified  : Fri Mar 29 00:45:21 2019
 * Computer  : ZVPIXX
 * System    : Linux 4.15.0-39-lowlatency x86_64 x86_64
 *
 * Purpose   : Computes a 8-bit CRC checksum for the LDC 13xx/16xx EVMs (e.g FDC2214EVM)
 *             using the configuration:
 *             - Width         = 8
 *             - Poly          = 0x07 (z^8 + z^2 + z + 1)
 *             - XorIn         = 0x00
 *             - ReflectIn     = False
 *             - XorOut        = 0x00
 *             - ReflectOut    = False
 *             - Algorithm     = table-driven
 * Generated by https://pycrc.org/pycrc.html
 */

#include <stdio.h>  /* printf() */
#include <stdlib.h>  /* For EXIT_FAILURE, EXIT_SUCCESS, malloc etc. */
#include <string.h> /* String operations */

#include "crc8.h"

/* Static table used for the table_driven implementation. */
static const unsigned char crc_table[256] = {
	0x00, 0x07, 0x0E, 0x09, 0x1C, 0x1B, 0x12, 0x15, 0x38, 0x3F, 0x36, 0x31, 0x24, 0x23, 0x2A, 0x2D,
	0x70, 0x77, 0x7E, 0x79, 0x6C, 0x6B, 0x62, 0x65, 0x48, 0x4F, 0x46, 0x41, 0x54, 0x53, 0x5A, 0x5D,
	0xE0, 0xe7, 0xEE, 0xE9, 0xFC, 0xFB, 0xF2, 0xF5, 0xD8, 0xDF, 0xD6, 0xD1, 0xC4, 0xC3, 0xCA, 0xCD,
	0x90, 0x97, 0x9E, 0x99, 0x8C, 0x8B, 0x82, 0x85, 0xA8, 0xAF, 0xA6, 0xA1, 0xB4, 0xB3, 0xBA, 0xBD,
	0xC7, 0xC0, 0xC9, 0xCE, 0xDB, 0xDC, 0xD5, 0xD2, 0xFF, 0xF8, 0xF1, 0xF6, 0xE3, 0xE4, 0xED, 0xEA,
	0xB7, 0xB0, 0xB9, 0xBE, 0xAB, 0xAC, 0xA5, 0xA2, 0x8F, 0x88, 0x81, 0x86, 0x93, 0x94, 0x9D, 0x9A,
	0x27, 0x20, 0x29, 0x2E, 0x3B, 0x3C, 0x35, 0x32, 0x1F, 0x18, 0x11, 0x16, 0x03, 0x04, 0x0D, 0x0A,
	0x57, 0x50, 0x59, 0x5E, 0x4B, 0x4C, 0x45, 0x42, 0x6F, 0x68, 0x61, 0x66, 0x73, 0x74, 0x7D, 0x7A,
	0x89, 0x8E, 0x87, 0x80, 0x95, 0x92, 0x9B, 0x9C, 0xB1, 0xB6, 0xBF, 0xB8, 0xAD, 0xAA, 0xA3, 0xA4,
	0xF9, 0xFE, 0xF7, 0xF0, 0xE5, 0xE2, 0xEB, 0xEC, 0xC1, 0xC6, 0xCF, 0xC8, 0xDD, 0xDA, 0xD3, 0xD4,
	0x69, 0x6E, 0x67, 0x60, 0x75, 0x72, 0x7B, 0x7C, 0x51, 0x56, 0x5F, 0x58, 0x4D, 0x4A, 0x43, 0x44,
	0x19, 0x1E, 0x17, 0x10, 0x05, 0x02, 0x0B, 0x0C, 0x21, 0x26, 0x2F, 0x28, 0x3D, 0x3A, 0x33, 0x34,
	0x4E, 0x49, 0x40, 0x47, 0x52, 0x55, 0x5C, 0x5B, 0x76, 0x71, 0x78, 0x7F, 0x6A, 0x6D, 0x64, 0x63,
	0x3E, 0x39, 0x30, 0x37, 0x22, 0x25, 0x2C, 0x2B, 0x06, 0x01, 0x08, 0x0F, 0x1A, 0x1D, 0x14, 0x13,
	0xAE, 0xA9, 0xA0, 0xA7, 0xB2, 0xB5, 0xBC, 0xBB, 0x96, 0x91, 0x98, 0x9F, 0x8A, 0x8D, 0x84, 0x83,
	0xDE, 0xD9, 0xD0, 0xD7, 0xC2, 0xC5, 0xCC, 0xCB, 0xE6, 0xE1, 0xE8, 0xEF, 0xFA, 0xFD, 0xF4, 0xF3
};


/* Calculate the CRC8 value with the data.
 *
 * \param[in] data     Pointer to a buffer of data_len bytes.
 * \param[in] data_len Number of bytes in the data buffer.
 * \return             The CRC8 value.
 */
unsigned char crc8(const void *data_ptr, unsigned int data_len) {
	const unsigned char *d = (const unsigned char *)data_ptr;
	unsigned int tbl_idx;

	unsigned char crc = crc_init();

	while (data_len--) {
		tbl_idx = crc ^ *d;
		crc = crc_table[tbl_idx] & 0xFF;
		d++;
	}
	return crc & 0xFF;
}

/* Calculate the CRC8 value on the HEX string */
unsigned char crc8_hex(const char *hex_ptr, unsigned int hex_len) {
	if (hex_len % 2 != 0) return 0; // not even

	char buf[hex_len/2+1];
	return crc8(hexToAscii(buf, sizeof buf, hex_ptr), hex_len/2);
}

/* Add CRC8 to the end of hex string*/
char *add_crc8_to_hexstring(char* hexCRC8, const char *hex_ptr, unsigned int hex_len) {
	if (hex_len % 2 != 0) return NULL; // not even

	char c8[3];
	snprintf(c8, 3, "%02X", crc8_hex(hex_ptr, hex_len));
	snprintf(hexCRC8, hex_len+3, "%s%2s", hex_ptr, c8);

	return hexCRC8;
}

/* Print CRC8 configuration */
void print_crc8_params(void) {
	char format[20];

	snprintf(format, sizeof(format), "%%-16s = 0x%%0%dllx\n", (unsigned int)(8 + 3) / 4);
	printf("%-16s = %d\n", "width", (unsigned int)8);
	printf(format, "poly", (unsigned long long int)0x07);
	printf("%-16s = %s\n", "reflect_in", "false");
	printf(format, "xor_in", (unsigned long long int)0x00);
	printf("%-16s = %s\n", "reflect_out", "false");
	printf(format, "xor_out", (unsigned long long int)0x00);
	printf(format, "crc_mask", (unsigned long long int)0xff);
	printf(format, "msb_mask", (unsigned long long int)0x80);
}

// There are _many_ ways to do this step.
static unsigned int char2int(int ch) {
	static const char Hex[] = "0123456789ABCDEF0123456789abcdef";

	char *p = memchr(Hex, ch, 32); // search for the first occurrence of ch in the first n bytes of string pointed
	if (p) {
		return (unsigned int) (p - Hex) % 16;
	}
	return (unsigned int) -1;  // error value
}

/* Convert hex string to ascii string. Return NULL with ill-formed string */
char *hexToAscii(char *str_ptr, unsigned int str_size, const char *hex_ptr) {
	if (str_size <= 0) return NULL;

	char *p = str_ptr;

	while (*hex_ptr) {
		if (str_size == 0) return NULL;
		str_size--;

		unsigned int msb = char2int(*hex_ptr++);
		if (msb > 15) return NULL;
		unsigned int lsb = char2int(*hex_ptr++);
		if (lsb > 15) return NULL;
		char ch = (char) (msb * 16 + lsb);

		// Optionally test for embedded null character
		// if (ch == 0) return NULL;

		*p++ = ch;
	}
	*p = '\0'; // add null character

	return str_ptr;
}

/* Convert ascii string to hex string */
char *asciiToHex(char *hex_ptr, unsigned int hex_size, const char *str_ptr) {
	if (hex_size <= 0 || (hex_size-1) % 2 != 0) return NULL;

	for (unsigned int i=0; i<(hex_size-1)/2; i++)
		sprintf(hex_ptr+i*2, "%02X", str_ptr[i] & 0xFF);

	return hex_ptr;
}

/* Convert hex string to binary string. Return NULL if bin_size is too small */
char *hexToBin(char *bin_ptr, unsigned int bin_size, const char *hex_ptr) {
	memset(&bin_ptr[0], 0, bin_size);
	bin_size--;
	while (*hex_ptr) {
		if (bin_size < 4) return NULL;
		bin_size -= 4;
		switch (*hex_ptr++) {
			case '0':
				strcat(bin_ptr, "0000"); break;
			case '1':
				strcat(bin_ptr, "0001"); break;
			case '2':
				strcat(bin_ptr, "0010"); break;
			case '3':
				strcat(bin_ptr, "0011"); break;
			case '4':
				strcat(bin_ptr, "0100"); break;
			case '5':
				strcat(bin_ptr, "0101"); break;
			case '6':
				strcat(bin_ptr, "0110"); break;
			case '7':
				strcat(bin_ptr, "0111"); break;
			case '8':
				strcat(bin_ptr, "1000"); break;
			case '9':
				strcat(bin_ptr, "1001"); break;
			case 'a': case 'A':
				strcat(bin_ptr, "1010"); break;
			case 'b': case 'B':
				strcat(bin_ptr, "1011"); break;
			case 'c': case 'C':
				strcat(bin_ptr, "1100"); break;
			case 'd': case 'D':
				strcat(bin_ptr, "1101"); break;
			case 'e': case 'E':
				strcat(bin_ptr, "1110"); break;
			case 'f': case 'F':
				strcat(bin_ptr, "1111"); break;
			default:
				printf("Invalid hexadecimal input.");
		}
	}
	return bin_ptr;
}

/* Convert bin string to hex string. hexSTring must be at least strlen(ibinStr)/4 + 1 bytes */
char *binToHex(char *hex_ptr, unsigned int hex_size, const char *bin_ptr) {
	if (hex_size <= 0) return NULL;

	static const char hex[] = "0123456789ABCDEF";

	int bin_size = strlen(bin_ptr);
	unsigned int length = (unsigned int)bin_size / 4;
	unsigned int rest = (unsigned int)bin_size % 4;

	if ( (!rest && hex_size<length+1) || (rest && hex_size<length+2) )
		return NULL;

	char *h = hex_ptr;

	int current = 0;
	if (rest) { // handle not multiple of 4
		while (rest--) {
			current = (current << 1) + (*bin_ptr - '0');
			bin_ptr++;
		}
		*h++ = hex[current];
	}

	int i;
	while (length--) {
		current = 0;
		for (i = 0; i < 4; ++i) {
			current = (current << 1) + (*bin_ptr - '0');
			bin_ptr++;
		}
		*h++ = hex[current];
	}

	*h = '\0'; // add null character

	return hex_ptr;
}

// The same as strtoul(const char *bin_ptr, NULL, 2)
unsigned long binToInt(const char *bin_ptr) {
	unsigned long i = 0, size = 8*sizeof(unsigned long);
	while ( (size--) && ((*bin_ptr == '0') || (*bin_ptr == '1')) ) {
		i <<= 1; // shift left is the same than multiply by 2
		if ( *bin_ptr == '1' ) i++;
		bin_ptr++;
	}
	return i;
}

// Converts an unsigned long value int to the string in str according to the given base,
// which must be between 2 and 36 inclusive, or be the special value 0.
char *ulToStr(unsigned long value, char *ptr, int base) {
	unsigned long t = 0, res = 0;
	unsigned long tmp = value;
	int count = 0;

	if (ptr == NULL)
		return NULL;

	if (tmp == 0)
		count++;

	while (tmp > 0) {
		tmp = tmp/base;
		count++;
	}

	ptr += count;
	*ptr = '\0';

	do {
		res = value - base * (t = value/base);
		if (res < 10)
			*--ptr = '0' + res;
		else if ((res >= 10) && (res < 16))
			*--ptr = 'A' - 10 + res;
	} while ((value = t) != 0);

	return ptr;
}
